### ISSUE TITLE
Use invoice.macaroon instead of admin.macaroon

### ISSUE THREAD

**Issue by seth586** [sparkswap/sparkswap-desktop#2]
If I am only buying and depositing on lightning, I should only give credentials to sparkswap to deposit, not withdraw!

Please allow the use of invoice.macaroon in place of admin.macaroon!

**Comment by treygriffith** [comment]
The Sparkswap app also uses `connectPeer` to be able to open channels without forcing you to open a port. We're talking with the LND team about creating a macaroon that allows `connectPeer` without Admin privileges, but currently it's not possible.

We completely agree with the concern, and we'll work to alleviate this if we can through more fine-grained settings, and hopefully resolve with a new macaroon.

**Comment by seth586** [comment]
If were uploading macaroons we're at power user level, perhaps a popup requesting a manual `connectPeer` operation when necessary in the interim? 

On a desktop environment most people are using RTL to manage their nodes, and a `connectPeer` request is an easy process thru that UI.

**Comment by seth586** [comment]
Looks like the macaroon bakery will be in the next lnd `v0.9.0-beta` release!

**Comment by dannypaz** [comment]
@seth586 this is a tough situation. We can request the user to `connectPeer` and prevent any action until they have done so, but that might be bad UX. Requesting anything manually removes user friendliness from the app and lightning itself.

Macaroon bakery would unfortunately require the user to run something manually (to generate a macaroon for invoices), which runs into the same problem.

However, in the current iteration of the app, you can specify _any_ macaroon (we dont do any validation of admin macaroon). As long as your macaroon has the correct permissions, it would work.

FWIW This is still on a radar

**Comment by seth586** [comment]
Solution!
```
lncli bakemacaroon --save_to=spark.macaroon invoices:read invoices:write address:read address:write onchain:read offchain:read message:read peers:read info:read signer:read peers:write
```
That generated a macaroon that can receive funds, and prevents sparkswap from sending funds!

**Comment by dannypaz** [comment]
@seth586 very cool! We will add this to the docs and prompt users for this functionality if its available.
