### ISSUE TITLE
Can't Run Sparkswap Desktop

### ISSUE THREAD

**Issue by supertestnet** [sparkswap/sparkswap-desktop#3]
I downloaded the appimage on a fresh installation of debian, made it executable using chmod a+x, and tried to execute it. I got this error message:

[4388:1201/140302.353000:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_SparksBpSYBG/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

I don't see a directory called .mount_SparksBpSYBG in my /tmp/ directory. What should I do?

**Comment by dannypaz** [comment]
Hey @supertestnet !! Thanks for giving us the heads up. I haven't seen this error before, but https://github.com/electron/electron/issues/17972 looks like its related. I'll see if there is something we (sparkswap) can do for the app (aside from using `--no-sandbox`)

I'll continue to post updates on this issue if there is a resolution. FWIW this looks to be affecting debian (not ubuntu to my knowledge)

**Comment by dannypaz** [comment]
Additionally, this tutorial has some decent info on the cause of the error: https://equk.co.uk/2018/04/02/forcing-namespace-sandbox-in-chrome-electron

**Comment by supertestnet** [comment]
Your second link had the solution I needed:

sudo sh -c "echo 'kernel.unprivileged_userns_clone=1' > /etc/sysctl.d/00-userns.conf"

After running that, and restarting, Sparkswap started up perfectly. 👍
